export const COLORS =  {
    BACKGROUND_WHITE: '#121214',
    SECONDARY_BACKGROUND: '#232429',

    TEXT_BASE_COLOR: '#ffffff',
    TEXT_SECONDARY_COLOR: '#8727ba',

    ICONS_PRIMARY_COLOR: '#db5c07',
    ICONS_SECONDARY_COLOR: '#706d35',
    ICONS_WHITE_COLOR: '#ffffff',

    BUTTON_PRIMARY_COLOR: '#db5c07',
    BUTTON_SECONDARY_COLOR: '#c4c3af',
}