export const COLORS =  {
    BACKGROUND_WHITE: '#ffff',
    SECONDARY_BACKGROUND: '#d7dade',

    TEXT_BASE_COLOR: '#000000',
    TEXT_SECONDARY_COLOR: '#424345',

    ICONS_PRIMARY_COLOR: '#165ae0',
    ICONS_SECONDARY_COLOR: '#babdc2',
    ICONS_BLACK_COLOR: '#000000',

    BUTTON_PRIMARY_COLOR: '#e8dd15',
    BUTTON_SECONDARY_COLOR: '#c4c3af',
}